#!/bin/bash
RED='\033[1;31m' 
GREEN='\033[1;32m' 
BOLD='\033[1;1m'
NC='\033[0m' # No Color

clear

echo -e "$GREEN -----Runnning c++ file .......\n\n $NC"
g++ "$1"

echo -e "$GREEN runnig resultant a.out file\n\n......  $NC"
./a.out

echo -e "\n\n$GREEN program  ran  successfully $NC"

